### PR TITLE
Updated some inconsistent styles, cleaned up project.

### PR DESCRIPTION
**Pull request by thismat**
# Reasons

The newer version of Visual Studio seemed to have fixed the theme flicker issues. I also noticed some inconsistent styles that needed adjusted.

# Changes

- Account ID Card background now uses the standard block
- Fixed hyperliniks for the info bar to not blend into the background color
- Removed vssettings file. Trying to get everything self contained in the theme now
- Added the nord icon to make it look better in the extensions list
- Updated the readme to include better installation process

# Considerations

I'd like to keep working a bit on the theme and get it building with github actions and submitted to the VS Marketplace. I figure it's got some work still that it needs done before doing so, but it would make keeping the theme up to date smoother. What do you think?

### CODE REVIEW

**Comment by jwendl** [comment]
Thank you for the PR 👏 

Yeah I think github actions to the marketplace would rock. Would you want that as a separate PR or included in this one?

**Comment by thismat** [comment]
Well, I found some things I want to clean up. The Razer syntax for instance is really bad right now. So I'm going to be working on the theme a bit more actually. 

We could probably hold off on the this PR until that's ready and then maybe a new PR after it's been solidified a bit before the build and marketplace push? Kind of up to you on that one.

**Comment by jwendl** [comment]
Ok will wait to merge until the clean up happens. I agree we can make the marketplace push a separate PR.

**Comment by thismat** [comment]
Okay look this over if you want. Fine tuned a bunch of stuff. More work to do but this is good to go for now I think.

**Comment by jwendl** [comment]
Thank you for the contribution - looks awesome!

**Pull request merged**
